version: "3.8"

services:
  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: consultadd
      MYSQL_DATABASE: fullstackprj
      MYSQL_USER: appuser
      MYSQL_PASSWORD: consultadd
    ports:
      - "3307:3306"
    networks:
      - app_network
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./FastAPIAssignment/
      dockerfile: Dockerfile
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://root:consultadd@db/fullstackprj
    depends_on:
      - db
    networks:
      - app_network

  frontend:
    build:
      context: ./LibraryBookMgmt/
      dockerfile: Dockerfile
    container_name: react_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:

volumes:
  mysql_data:
